os: linux
dist: trusty
sudo: false

language: python
python:
    - 2.7

addons:
  apt:
    packages:
    - texlive-fonts-recommended
    - texlive-latex-extra
    - texlive-fonts-extra
    - texlive-latex-recommended
    - dvipng
    - texlive-xetex

install:
#- apt-get install -y ipython ipython-notebook python-jinja2 python-pygments
- pip install ipython

before_script:
# Downloads GDrive tool locally (from https://github.com/prasmussen/gdrive)
- wget -L "https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download" -O gdrive-linux-x64
# Configure NBConvert to handle Unicodes
- mkdir -p ~/.ipython/profile_nbserver/
- echo "c = get_config()" > ~/.ipython/profile_nbserver/ipython_nbconvert_config.py
- echo "c.PDFPostProcessor.latex_command = [u'xelatex', u'{filename}']" >> ~/.ipython/profile_nbserver/ipython_nbconvert_config.py

script:
- mkdir output/
- cd output/
- ipython nbconvert --to latex --post PDF --config ~/.ipython/profile_nbserver/ipython_nbconvert_config.py ../notebooks/*/*.ipynb
#- pdflatex -interaction=nonstopmode -halt-on-error -output-directory . ../tex/*.tex

