os: linux
dist: xenial

language: python
python:
    - 3.6

env:
  global:
    - DEPLOY_REPO=zlig/masters-thesis
    - DEPLOY_FILES=output/*.pdf

branches:
    only:
    - master
    - /v\d+\.\d+[a-z]/

addons:
  apt:
    packages:
    - texlive-fonts-recommended
    - texlive-fonts-extra
    - texlive-latex-extra
    - texlive-latex-recommended
    - texlive-luatex
    - texlive-pstricks
    - texlive-xetex
    - dvipng
    - pandoc
    - ca-certificates
    - python-setuptools
    - fonts-lmodern
    - wget
    - xzdec

install:
#- apt-get install -y ipython ipython-notebook python-jinja2 python-pygments
- pip install "ipython[notebook]" --upgrade
- pip install nbconvert pypandoc
- pip install pygments

before_script:
# Downloads GDrive tool locally (from https://github.com/prasmussen/gdrive)
- wget -L "https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download" -O gdrive-linux-x64
# Configure NBConvert to handle Unicodes
- mkdir -p ~/.ipython/profile_nbserver/
- echo "c = get_config()" > ~/.ipython/profile_nbserver/ipython_nbconvert_config.py
- echo "c.PDFPostProcessor.latex_command = [u'xelatex', u'{filename}']" >> ~/.ipython/profile_nbserver/ipython_nbconvert_config.py
- pandoc --help

script:
# Converts Jupyter Notebooks
- ipython nbconvert --to PDF --config ~/.ipython/profile_nbserver/ipython_nbconvert_config.py notebooks/*/*.ipynb
- cp notebooks/*/*.pdf .

before_deploy:
  # Set up git user name and tag this commit
  - git config --local user.name "zlig"
  - git config --local user.email "noreply@example.com"
  - export TRAVIS_TAG=${TRAVIS_TAG:-$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)}
  - git tag $TRAVIS_TAG
deploy:
  provider: releases
  api_key: "${GITHUB_OAUTH_TOKEN}"
  file_glob: true
  file: "${DEPLOY_FILES}"
  skip_cleanup: true
  draft: true
