dist: trusty

before_install:
- sudo apt-get -qq update
- sudo apt-get install -y --no-install-recommends texlive-fonts-recommended texlive-latex-extra texlive-fonts-extra dvipng texlive-latex-recommended
- sudo apt-get install -y texlive-xetex
- sudo apt-get install -y ipython python-jinja2 python-pygments

before_script:
# Downloads GDrive tool locally (from https://github.com/prasmussen/gdrive)
- wget -L "https://docs.google.com/uc?id=0B3X9GlR6EmbnQ0FtZmJJUXEyRTA&export=download" -O gdrive-linux-x64
# Configure NBConvert to handle Unicodes
- mkdir -p ~/.ipython/profile_nbserver/
- echo "set c.PDFPostProcessor.latex_command = [u'xelatex', u'{filename}']" > ~/.ipython/profile_nbserver/ipython_nbconvert_config.py

script:
- mkdir output/
- cd output/
- ipython nbconvert --to latex --post PDF --config ~/.ipython/profile_nbserver/ipython_nbconvert_config.py ../notebook/*/*.ipynb
#- pdflatex -interaction=nonstopmode -halt-on-error -output-directory . ../tex/*.tex

